FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.12.0-cpu-py310-vg

ADD ./vg.py /opt/ml/code/vg.py
ADD ./requirements.txt /opt/ml/code/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /opt/ml/code/requirements.txt

ENV SAGEMAKER_PROGRAM vg.py

